version: "3"

services:
  jenkins:
    image: jenkins/jenkins:latest
    restart: always
    user: root
    environment:
      - HOME=/var/jenkins_home
      - JENKINS_HOME=/var/jenkins_home
      - JAVA_OPTS=
          -Djenkins.install.runSetupWizard=false
          -Djava.awt.headless=true
      - DOCKER_HOST=tcp://docker:2375
      - PLUGINS=
          workflow-aggregator
          job-dsl
          maven-plugin
          pipeline-maven
          matrix-auth
          antisamy-markup-formatter
          docker-plugin
          greenballs
          ansicolor
          git
    ports:
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
      - dind_bin:/usr/local/sbin
    entrypoint: /bin/bash
    command:
      - -c
      - >-
          /usr/local/bin/install-plugins.sh $${PLUGINS};
          /sbin/tini -- /usr/local/bin/jenkins.sh
    depends_on:
      - docker

  docker:
    image: "docker:dind"
    privileged: true
    volumes:
    - dind_bin:/usr/local/bin
    - dind_data:/var/lib/docker

volumes:
    jenkins_data:
    dind_data:
    dind_bin:
