version: "3"

services:
  jenkins-plugins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_plugins:/usr/share/jenkins/ref/plugins
    user: root
    command: /usr/local/bin/install-plugins.sh
      workflow-aggregator
      job-dsl
      greenballs
      ansicolor
      git

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    environment:
      - JAVA_OPTS=
          -Djenkins.install.runSetupWizard=false
          -Djava.awt.headless=true
      - DOCKER_HOST=tcp://docker:2375
    ports:
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_plugins:/usr/share/jenkins/ref/plugins
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
      - dind_bin:/usr/local/sbin
    entrypoint: bash -c "while ping -c1 jenkins-plugins &>/dev/null; do sleep 1; done; /sbin/tini -- /usr/local/bin/jenkins.sh"
    depends_on:
      - jenkins-plugins
      - docker

  docker:
    image: "docker:dind"
    privileged: true
    volumes:
    - dind_bin:/usr/local/bin
    - dind_data:/var/lib/docker

volumes:
    jenkins_data:
    jenkins_plugins:
    dind_data:
    dind_bin:
