version: "2"

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    environment:
      - JAVA_OPTS=
          -Djenkins.install.runSetupWizard=false
          -Djava.awt.headless=true
    ports:
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
    logging:
      driver: journald
      options:
        tag: jenkins
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
    restart: always
    volumes:
      - nexus_data:/nexus-data

volumes:
    jenkins_data:
    nexus_data:
