version: "2.3"

services:
  centosvm:
    build:
      context: .
      dockerfile: CentOS.SSHD.Dockerfile
    scale: 1
    volumes:
     - /sys/fs/cgroup
    cap_add:
     - SYS_ADMIN

  ubuntuvm:
    build:
      context: .
      dockerfile: Ubuntu.SSHD.Dockerfile
    scale: 1
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup
    cap_add:
     - SYS_ADMIN
