route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: siarhei_beliakou@epam.com
    from: sbeliakou@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "sbeliakou"
    auth_identity: "sbeliakou@gmail.com"
    auth_password: "*****"
